name: Update documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  update_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN}}
        run: python generate_docs.py -c generate_docs.yaml -t "$GH_ACCESS_TOKEN"
      
      - name: Push changes
        run: |
          git config --global user.name "GitHub"
          git config --global user.email "noreply@github.com"
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit. Exiting."
            exit 0
          fi
          git add -A
          git commit -m "Update pages"
          git push
