name: Update documentation

on:
  repository_dispatch
  workflow_dispatch

jobs:
  update_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN}}
        run: python generate_docs.py -c generate_docs.yaml -t "$GH_ACCESS_TOKEN"
      
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update docs
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          branch: updated-docs
          delete-branch: true
          title: 'Update docs'
          body: |
            This automated PR updates the documentation pages.
          labels: |
            pages update
            automated pr

      - name: Approve pull request
        if: (steps.cpr.outputs.pull-request-operation == 'created' ||	steps.cpr.outputs.pull-request-operation == 'updated')
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}

      - name: Merge pull request
        if: (steps.cpr.outputs.pull-request-operation == 'created' ||	steps.cpr.outputs.pull-request-operation == 'updated')
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash